[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # ensure npm installs devDependencies on Netlify
  NPM_FLAGS = "--include=dev"
  legacy-peer-deps=true